[
  {
    "id": "I_kwDOMT5cIs6kMyCl",
    "number": 1378,
    "title": "Postgres adapter doesnt apply settings",
    "body": "**Describe the bug**\r\n\r\n<!-- A clear and concise description of what the bug is. -->\r\nThe postgres provider doesn't even apply `app.settings` defined in the `schema.sql` file which means the embedding dimensions is always 384 regardless of what embeddings settings you have.\r\n\r\n\r\n**To Reproduce**\r\n\r\nUse openai embeddings which are 1532 dimensions. The database will complain because the tables are intialized with 384 dimensions.\r\n\r\n<!-- Steps to reproduce the behavior. -->\r\n\r\n**Expected behavior**\r\n\r\nIt works\r\n\r\n<!-- A clear and concise description of what you expected to happen. -->\r\n\r\n**Screenshots**\r\n\r\n<!-- If applicable, add screenshots to help explain your problem. -->\r\n\r\n**Additional context**\r\n\r\n<!-- Add any other context about the problem here. -->\r\n",
    "state": "OPEN",
    "createdAt": "2024-12-22T19:45:19Z",
    "updatedAt": "2024-12-22T19:45:19Z",
    "author": {
      "login": "ryanleecode",
      "avatarUrl": "https://avatars.githubusercontent.com/u/21375952?u=24f232e3e3356e214d1464bde3bd64ffe79e0090&v=4"
    },
    "labels": [
      {
        "id": "LA_kwDOMT5cIs8AAAABrA0qWA",
        "name": "bug",
        "color": "d73a4a",
        "description": "Something isn't working"
      }
    ],
    "comments": []
  },
  {
    "id": "I_kwDOMT5cIs6kMtjC",
    "number": 1376,
    "title": "Postgres Adapter schema check is nonsensical",
    "body": "**Describe the bug**\r\n\r\n<!-- A clear and concise description of what the bug is. -->\r\n\r\nThe following check is nonsensical because we already do `IF NOT EXIST` checks within the sql. If one of the tables were dropped, say for example the `memories` table because we want to change the vector dimensions, it wouldn't be recreated due to this check.\r\n\r\n```ts\r\n// Check if schema already exists (check for a core table)\r\nconst { rows } = await client.query(`\r\n    SELECT EXISTS (\r\n        SELECT FROM information_schema.tables\r\n        WHERE table_name = 'rooms'\r\n    );\r\n`);\r\n\r\n\r\nif (!rows[0].exists) {\r\n    const schema = fs.readFileSync(\r\n        path.resolve(__dirname, \"../schema.sql\"),\r\n        \"utf8\"\r\n    );\r\n    await client.query(schema);\r\n}\r\n```\r\n\r\nhttps://github.com/elizaOS/eliza/blob/4c658d7d70433fdcb2feeffe879429eaef10685d/packages/adapter-postgres/src/index.ts#L192C13-L206C14\r\n\r\n**To Reproduce**\r\n\r\n<!-- Steps to reproduce the behavior. -->\r\n\r\n**Expected behavior**\r\n\r\n<!-- A clear and concise description of what you expected to happen. -->\r\n\r\n**Screenshots**\r\n\r\n<!-- If applicable, add screenshots to help explain your problem. -->\r\n\r\n**Additional context**\r\n\r\n<!-- Add any other context about the problem here. -->\r\n",
    "state": "OPEN",
    "createdAt": "2024-12-22T18:56:14Z",
    "updatedAt": "2024-12-22T18:56:14Z",
    "author": {
      "login": "ryanleecode",
      "avatarUrl": "https://avatars.githubusercontent.com/u/21375952?u=24f232e3e3356e214d1464bde3bd64ffe79e0090&v=4"
    },
    "labels": [
      {
        "id": "LA_kwDOMT5cIs8AAAABrA0qWA",
        "name": "bug",
        "color": "d73a4a",
        "description": "Something isn't working"
      }
    ],
    "comments": []
  },
  {
    "id": "I_kwDOMT5cIs6kMF88",
    "number": 1372,
    "title": "Bot Doesn't Respond to Tagged Tweets When Running in Docker",
    "body": "When I run the bot using `npm start`, everything works perfectly: it tweets and responds to tagged tweets as expected. However, when I run the bot inside Docker, I encounter the following issues:\r\n\r\nEnvironment Variable: The `OPENAI_API_KEY ` is required when running the bot in Docker (`docker compose up`) , but it's not needed when running it directly (without Docker).\r\n\r\nTweeting: The bot tweets without any issues when running in Docker.\r\n\r\nResponse to Tagged Tweets: The problem arises when the bot is supposed to respond to tweets it's tagged in. While it tweets fine, it doesn't respond to any tagged tweets.\r\n\r\nI’ve checked the logs, and everything seems normal—there are no visible errors.\r\n\r\nCould anyone help identify what might be causing this issue when running the bot inside Docker?",
    "state": "OPEN",
    "createdAt": "2024-12-22T12:24:33Z",
    "updatedAt": "2024-12-22T12:24:33Z",
    "author": {
      "login": "usama-saeed831",
      "avatarUrl": "https://avatars.githubusercontent.com/u/14342066?v=4"
    },
    "labels": [
      {
        "id": "LA_kwDOMT5cIs8AAAABrA0qWA",
        "name": "bug",
        "color": "d73a4a",
        "description": "Something isn't working"
      }
    ],
    "comments": []
  },
  {
    "id": "I_kwDOMT5cIs6kL6A5",
    "number": 1370,
    "title": "imageSettings in character files do not currently work (providing fix PR)",
    "body": "**Describe the bug**\r\nImage settings in character files do not currently work.\r\n\r\n**To Reproduce**\r\n\r\nTo reproduce just try setting character file settings like \r\n\r\n![image](https://github.com/user-attachments/assets/821e6752-6f9c-4c69-ae0d-e008a04c78b6)\r\n\r\nand then generating an image. You will always get the default settings because they are not being passed from the character file.\r\n\r\n\r\n**Expected behavior**\r\n\r\nExpected behavior would be for these image settings to be passed on when generating an image.\r\n\r\n**Screenshots**\r\n\r\n<!-- If applicable, add screenshots to help explain your problem. -->\r\n\r\n**Additional context**\r\n\r\nI'm providing a fix right now. PR incoming.\r\n",
    "state": "OPEN",
    "createdAt": "2024-12-22T10:11:37Z",
    "updatedAt": "2024-12-22T10:11:37Z",
    "author": {
      "login": "proteanx",
      "avatarUrl": "https://avatars.githubusercontent.com/u/29043582?u=d2261c451984df04b46d6fca1261eb8d245de59b&v=4"
    },
    "labels": [
      {
        "id": "LA_kwDOMT5cIs8AAAABrA0qWA",
        "name": "bug",
        "color": "d73a4a",
        "description": "Something isn't working"
      }
    ],
    "comments": []
  },
  {
    "id": "I_kwDOMT5cIs6kL3qJ",
    "number": 1368,
    "title": "Google unsupported?",
    "body": "**Describe the bug**\r\n\r\n [\"⛔ Error: Failed to get token - unsupported model provider: google\"] \r\n\r\n**To Reproduce**\r\n.env\r\nGOOGLE_API_KEY=XXXXXXXXXXX\r\n\r\ntrump.character.json\r\n    \"name\": \"trump\",\r\n    \"clients\": [\"direct\"],\r\n    \"modelProvider\": \"google\",\r\n    \"settings\": {\r\n        \"secrets\": {},\r\n        \"voice\": {\r\n            \"model\": \"gemini-1.5-flash\"\r\n\r\n**Expected behavior**\r\n\r\n\"⛔ Error: Failed to get token - unsupported model provider: google\"] \r\n\r\n**Additional context**\r\n\r\nIs Google supported??? Do I need to change anything else to make Google work?\r\n",
    "state": "OPEN",
    "createdAt": "2024-12-22T09:44:39Z",
    "updatedAt": "2024-12-22T09:44:39Z",
    "author": {
      "login": "Sam43215",
      "avatarUrl": "https://avatars.githubusercontent.com/u/95595581?v=4"
    },
    "labels": [
      {
        "id": "LA_kwDOMT5cIs8AAAABrA0qWA",
        "name": "bug",
        "color": "d73a4a",
        "description": "Something isn't working"
      }
    ],
    "comments": []
  },
  {
    "id": "I_kwDOMT5cIs6kLz84",
    "number": 1367,
    "title": "v0.1.7 , Gitpod, default settings, eliza agent gets stuck when generating response",
    "body": "**Describe the bug**\r\n\r\nWhen I run the gitpod with default settings, the default agent starts , it downloads the local LM model , but unable to generate responce\r\n\r\n**To Reproduce**\r\n\r\nRun the gitpod with default setting , no .env modifications , with default character. \r\nwhen it is complete . running \"pnpm start\" \r\nand opening another termincal with \"pnpm start:client\"\r\nTo generate response it downloads the Language model but gets stuck in a loop or something and keeps printing \r\n\"```json\" over and over in main terminal and no reponse is generated on the chat client \r\n\r\n**Expected behavior**\r\n\r\nit should generate a response in the chat\r\n\r\n**Screenshots**\r\n\r\n![image](https://github.com/user-attachments/assets/948ec4c0-74cb-4890-b3fd-8ae791e2ef5e)\r\n\r\n\r\n**Additional context**\r\n\r\n<!-- Add any other context about the problem here. -->\r\n",
    "state": "OPEN",
    "createdAt": "2024-12-22T09:00:23Z",
    "updatedAt": "2024-12-22T09:00:23Z",
    "author": {
      "login": "onlyzerosonce",
      "avatarUrl": "https://avatars.githubusercontent.com/u/29201415?v=4"
    },
    "labels": [
      {
        "id": "LA_kwDOMT5cIs8AAAABrA0qWA",
        "name": "bug",
        "color": "d73a4a",
        "description": "Something isn't working"
      }
    ],
    "comments": []
  },
  {
    "id": "I_kwDOMT5cIs6kLxKM",
    "number": 1363,
    "title": "Support better in-monorepo navigation with custom conditions",
    "body": "**Is your feature request related to a problem? Please describe.**\r\n\r\nDoing go to definition always go to the d.ts file within the monorepo which is annoying.\r\n\r\n<!-- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] -->\r\n\r\n**Describe the solution you'd like**\r\n\r\nWe can use custom conditions in tsconfig to point directly to the TS File\r\n\r\n<!-- A clear and concise description of what you want to happen. -->\r\n\r\n**Describe alternatives you've considered**\r\n\r\n<!-- A clear and concise description of any alternative solutions or features you've considered. -->\r\n\r\n**Additional context**\r\n\r\nhttps://colinhacks.com/essays/live-types-typescript-monorepo",
    "state": "OPEN",
    "createdAt": "2024-12-22T08:25:49Z",
    "updatedAt": "2024-12-22T08:25:59Z",
    "author": {
      "login": "ryanleecode",
      "avatarUrl": "https://avatars.githubusercontent.com/u/21375952?u=24f232e3e3356e214d1464bde3bd64ffe79e0090&v=4"
    },
    "labels": [
      {
        "id": "LA_kwDOMT5cIs8AAAABrA0qYA",
        "name": "enhancement",
        "color": "a2eeef",
        "description": "New feature or request"
      }
    ],
    "comments": []
  },
  {
    "id": "I_kwDOMT5cIs6kLSHX",
    "number": 1349,
    "title": "Vector missmatch sqlite (when trying to use TTS)",
    "body": "**Describe the bug**\r\n\r\nerror when trying to use text to speech\r\n\r\n**To Reproduce**\r\n\r\ntalk in discord voice channel asking for a response\r\n\r\n**Expected behavior**\r\n\r\nsoundfile to be generated and played as  a reply\r\n\r\n**Screenshots**\r\n\r\n![image](https://github.com/user-attachments/assets/bdf663e6-ff0e-4063-9a14-d7bae65757e2)\r\n\r\n\r\n**Additional context**\r\n\r\nIt was working yesterday and i dont believe i've changed anything related",
    "state": "CLOSED",
    "createdAt": "2024-12-22T00:37:41Z",
    "updatedAt": "2024-12-22T03:41:35Z",
    "author": {
      "login": "vincentskele",
      "avatarUrl": "https://avatars.githubusercontent.com/u/147941271?u=7d01a4b50ee427df19e9b31bb0273500b71f72d0&v=4"
    },
    "labels": [
      {
        "id": "LA_kwDOMT5cIs8AAAABrA0qWA",
        "name": "bug",
        "color": "d73a4a",
        "description": "Something isn't working"
      }
    ],
    "comments": [
      {
        "id": "IC_kwDOMT5cIs6YfNe8",
        "author": "vincentskele",
        "body": "deleted my db now it works"
      }
    ]
  }
]
