[
  {
    "id": "I_kwDOMT5cIs6kppJj",
    "number": 1563,
    "title": "spades",
    "body": "**Is your feature request related to a problem? Please describe.**\n\n<!-- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] -->\n\n**Describe the solution you'd like**\n\n<!-- A clear and concise description of what you want to happen. -->\n\n**Describe alternatives you've considered**\n\n<!-- A clear and concise description of any alternative solutions or features you've considered. -->\n\n**Additional context**\n\n<!-- Add any other context or screenshots about the feature request here. -->\n",
    "state": "OPEN",
    "createdAt": "2024-12-29T19:33:57Z",
    "updatedAt": "2024-12-29T19:34:23Z",
    "author": {
      "login": "Dereichi",
      "avatarUrl": "https://avatars.githubusercontent.com/u/193001572?v=4"
    },
    "labels": [
      {
        "id": "LA_kwDOMT5cIs8AAAABrA0qYA",
        "name": "enhancement",
        "color": "a2eeef",
        "description": "New feature or request"
      }
    ],
    "comments": [
      {
        "id": "IC_kwDOMT5cIs6Y4A2k",
        "author": "github-actions",
        "body": "Hello @Dereichi! Welcome to the ai16z community. Thank you for opening your first issue; we appreciate your contribution. You are now a ai16z contributor!"
      }
    ]
  },
  {
    "id": "I_kwDOMT5cIs6kpht1",
    "number": 1562,
    "title": "Telegram connection",
    "body": "How can I fix this?\r\n\r\nI just added my telegram bot token and character.ts clients to Add telegram.\r\n\r\nHowever when I pnpm start I get this error :\r\n\r\n“ SUCCESS\r\n   SUCCESS \r\n   Creating runtime for character \r\n   Hikari \r\n\r\n âœ“ SUCCESS\r\n   Agent ID \r\n   1004db53-bf1b-0d1a-ba4c-01d318a8197d \r\n\r\n [\"âœ“ Registering action: CONTINUE\"] \r\n\r\n [\"âœ“ Registering action: FOLLOW_ROOM\"] \r\n\r\n [\"âœ“ Registering action: UNFOLLOW_ROOM\"] \r\n\r\n [\"âœ“ Registering action: IGNORE\"] \r\n\r\n [\"âœ“ Registering action: NONE\"] \r\n\r\n [\"âœ“ Registering action: MUTE_ROOM\"] \r\n\r\n [\"âœ“ Registering action: UNMUTE_ROOM\"] \r\n\r\n â—Ž LOGS\r\n   Registering service: \r\n   browser \r\n\r\n â—Ž LOGS\r\n   Registering service: \r\n   image_description \r\n\r\n â—Ž LOGS\r\n   Registering service: \r\n   text_generation \r\n\r\n â—Ž LOGS\r\n   Registering service: \r\n   pdf \r\n\r\n â—Ž LOGS\r\n   Registering service: \r\n   speech_generation \r\n\r\n â—Ž LOGS\r\n   Registering service: \r\n   transcription \r\n\r\n â—Ž LOGS\r\n   Registering service: \r\n   video \r\n\r\n [\"âœ“ Server running at http://localhost:3000/\"] \r\n\r\n [\"âœ“ Service browser initialized successfully\"] \r\n\r\n [\"âœ“ Service image_description initialized successfully\"] \r\n\r\n [\"âœ“ Service text_generation initialized successfully\"] \r\n\r\n [\"âœ“ Service pdf initialized successfully\"] \r\n\r\n [\"âœ“ Service speech_generation initialized successfully\"] \r\n\r\n [\"âœ“ Service transcription initialized successfully\"] \r\n\r\n [\"âœ“ Service video initialized successfully\"] \r\n\r\n [\"â—Ž ðŸ“± Constructing new TelegramClient...\"] \r\n\r\n [\"â—Ž âœ… TelegramClient constructor completed\"] \r\n\r\n [\"â—Ž ðŸš€ Starting Telegram bot...\"] \r\n\r\n [\"â—Ž âœ¨ Telegram bot successfully launched and is running!\"] \r\n\r\n â›” ERRORS\r\n   â^]Œ Failed to launch Telegram bot: \r\n   {\"message\":\"request to https://api.telegram.org/bot7813398684:[REDACTED]/getMe failed, reason: \",\"type\":\"system\",\"errno\":\"ETIMEDOUT\",\"code\":\"ETIMEDOUT\"} \r\n\r\n â›” ERRORS\r\n   Error starting agent for character Hikari: \r\n   {\"message\":\"request to https://api.telegram.org/bot7813398684:[REDACTED]/getMe failed, reason: \",\"type\":\"system\",\"errno\":\"ETIMEDOUT\",\"code\":\"ETIMEDOUT\"} \r\n\r\nFetchError: request to https://api.telegram.org/bot7813398684:[REDACTED]/getMe failed, reason: \r\n    at ClientRequest.<anonymous> (/home/algorex/eliza-starter/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:1501:11)\r\n    at ClientRequest.emit (node:events:524:28)\r\n    at emitErrorEvent (node:_http_client:104:11)\r\n    at TLSSocket.socketErrorListener (node:_http_client:512:5)\r\n    at TLSSocket.emit (node:events:524:28)\r\n    at emitErrorNT (node:internal/streams/destroy:170:8)\r\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\r\n    at processTicksAndRejections (node:internal/process/task_queues:90:21)\r\n    at runNextTicks (node:internal/process/task_queues:69:3)\r\n    at listOnTimeout (node:internal/timers:555:9) {\r\n  type: 'system',\r\n  errno: 'ETIMEDOUT',\r\n  code: 'ETIMEDOUT'\r\n}\r\n â›” ERRORS\r\n   Error starting agents: \r\n   {\"message\":\"request to https://api.telegram.org/bot7813398684:[REDACTED]/getMe failed, reason: \",\"type\":\"system\",\"errno\":\"ETIMEDOUT\",\"code\":\"ETIMEDOUT\"} \r\n\r\n [\"â—Ž Chat started. Type 'exit' to quit.\"] \r\n\r\nYou: \r\n/home/algorex/eliza-starter/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:1501\r\n                        reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));\r\n                               ^\r\nFetchError: request to https://api.telegram.org/bot7813398684:[REDACTED]/getMe failed, reason: \r\n    at ClientRequest.<anonymous> (/home/algorex/eliza-starter/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:1501:11)\r\n    at ClientRequest.emit (node:events:524:28)\r\n    at emitErrorEvent (node:_http_client:104:11)\r\n    at TLSSocket.socketErrorListener (node:_http_client:512:5)\r\n    at TLSSocket.emit (node:events:524:28)\r\n    at emitErrorNT (node:internal/streams/destroy:170:8)\r\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\r\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {\r\n  type: 'system',\r\n  errno: 'ETIMEDOUT',\r\n  code: 'ETIMEDOUT'\r\n}\r\n\r\nNode.js v22.12.0\r\nâ€‰ELIFECYCLEâ€‰ Command failed with exit code 1.\r\n",
    "state": "OPEN",
    "createdAt": "2024-12-29T17:56:35Z",
    "updatedAt": "2024-12-29T17:56:58Z",
    "author": {
      "login": "ALGOREX-PH",
      "avatarUrl": "https://avatars.githubusercontent.com/u/55391597?u=ccba12da727b2b6df802248776c62b50983810e9&v=4"
    },
    "labels": [
      {
        "id": "LA_kwDOMT5cIs8AAAABrA0qWA",
        "name": "bug",
        "color": "d73a4a",
        "description": "Something isn't working"
      }
    ],
    "comments": [
      {
        "id": "IC_kwDOMT5cIs6Y37n7",
        "author": "github-actions",
        "body": "Hello @ALGOREX-PH! Welcome to the ai16z community. Thank you for opening your first issue; we appreciate your contribution. You are now a ai16z contributor!"
      }
    ]
  },
  {
    "id": "I_kwDOMT5cIs6kpb4z",
    "number": 1561,
    "title": "Duplicate key value violates unique constraint \"pg_extension_name_index\"",
    "body": "Hi All,\r\n\r\nI cloned the repository `https://github.com/elizaos/eliza.git` and checked out the `v0.1.7-alpha.1` tag. The database adapter I am using is the PostgreSQL vector DB, specifically the Docker image `pgvector/pgvector:pg16` from [Docker Hub](https://hub.docker.com/_/postgres).\r\n\r\nUpon running `pnpm start`, the PostgreSQL database is populated with all the required tables, but I encounter the following error (see the attached image):\r\n\r\n![Screenshot 2024-12-29 at 7 51 52 PM](https://github.com/user-attachments/assets/6f984be8-a5c2-4871-96c1-2051d82e8c66)\r\n\r\nThis issue occurs even when I do a fresh clone of the eliza project.\r\n\r\n**Environment Details:**\r\n\r\nNode version: `23.3.0`\r\npnpm version: `9.15.2`\r\nPostgreSQL Docker Image: `pgvector/pgvector:pg16`\r\n\r\nThanks in Advance!\r\n\r\n\r\n",
    "state": "OPEN",
    "createdAt": "2024-12-29T16:47:44Z",
    "updatedAt": "2024-12-29T16:48:09Z",
    "author": {
      "login": "digvjs",
      "avatarUrl": "https://avatars.githubusercontent.com/u/33622661?v=4"
    },
    "labels": [
      {
        "id": "LA_kwDOMT5cIs8AAAABrA0qWA",
        "name": "bug",
        "color": "d73a4a",
        "description": "Something isn't working"
      }
    ],
    "comments": [
      {
        "id": "IC_kwDOMT5cIs6Y32xQ",
        "author": "github-actions",
        "body": "Hello @digvjs! Welcome to the ai16z community. Thank you for opening your first issue; we appreciate your contribution. You are now a ai16z contributor!"
      }
    ]
  },
  {
    "id": "I_kwDOMT5cIs6kpBT2",
    "number": 1560,
    "title": "Feature: Add Swarm Agent Capabilities to Eliza",
    "body": "**Description**\r\nAdding a new type of “swarm agent” to the Eliza framework. The goal is to allow multiple agents to coordinate on tasks in a way similar to how single-character agents are currently configured, while supporting unique swarm features such as collective decision-making and interactions among multiple agents.\r\n\r\n**Motivation & Rationale**\r\n\r\nEliza currently supports single “character” agents with various providers, settings, and behaviours.\r\nA natural next step is to introduce the ability for multiple agents to work collectively (swarm) on tasks.\r\n\r\n**Proposed Feature Requirements**\r\n\r\n1. Swarm Agent Configuration\r\n\r\n_Support a dedicated configuration block for swarm agents in a manner similar to single-character agents._\r\n\r\n Allow specifying:\r\n- Number of agents in the swarm.\r\n- Provider definitions for each agent (could be the same or different).\r\n- Traditional settings (e.g., roles, personas, capabilities).\r\n- Additional swarm-specific settings (e.g., rules for agent coordination, speaker settings, collective decision-making thresholds).`\r\n\r\n\r\n2. Create Swarm Logic.\r\n\r\n- Configure and Execute swarms by importing the core package in external projects.\r\n- Allow all supported clients to use swarm logic without disrupting current flows(ex: the last agent in a twitter maker team will post as a singular agent akin to current implementation).\r\n- Write dedicated test suite or carefully extend the current tests to confirm proper handling of the majority of cases.\r\n\r\n\r\n3. Document feature:\r\n\r\n- How multiple agents can be spawned and coordinated. \r\n- How tasks or sub-tasks are delegated among swarm agents (e.g., parallel vs. sequential).\r\n- How swarm memory storage works.\r\n- Document possible flows.\r\n- How can the utility be extended further. \r\n\r\n",
    "state": "OPEN",
    "createdAt": "2024-12-29T11:45:06Z",
    "updatedAt": "2024-12-29T11:51:45Z",
    "author": {
      "login": "UD1sto",
      "avatarUrl": "https://avatars.githubusercontent.com/u/76160388?v=4"
    },
    "labels": [
      {
        "id": "LA_kwDOMT5cIs8AAAABrA0qYA",
        "name": "enhancement",
        "color": "a2eeef",
        "description": "New feature or request"
      }
    ],
    "comments": [
      {
        "id": "IC_kwDOMT5cIs6Y3jWZ",
        "author": "UD1sto",
        "body": "Please comment here if you are interested in partnering on this effort"
      }
    ]
  },
  {
    "id": "I_kwDOMT5cIs6kosEW",
    "number": 1557,
    "title": "Eliza X Posting GENERATE_IMAGE in her tweets, should attach image to tweet post instead",
    "body": "**Describe the bug**\r\n\r\n<!-- A clear and concise description of what the bug is. -->\r\nEliza is outputting text to GENERATE_IMAGE instead of actually generating an image on twitter\r\n- ex [here](https://x.com/elizawakesup/status/1873253691618410976) and [here](https://x.com/elizawakesup/status/1873173558459081096)\r\n\r\n**To Reproduce**\r\n\r\n<!-- Steps to reproduce the behavior. -->\r\n\r\n\r\n**Expected behavior**\r\na picture should be attached to the tweet instead of the GENERATE_IMAGE text\r\n<!-- A clear and concise description of what you expected to happen. -->\r\n\r\n**Screenshots**\r\n![image](https://github.com/user-attachments/assets/553b0e9c-8a84-4f50-9e90-9b0e53bb3a93)\r\n\r\n<!-- If applicable, add screenshots to help explain your problem. -->\r\n\r\n**Additional context**\r\n\r\n<!-- Add any other context about the problem here. -->\r\n",
    "state": "OPEN",
    "createdAt": "2024-12-29T06:43:55Z",
    "updatedAt": "2024-12-29T16:44:09Z",
    "author": {
      "login": "yqj2k",
      "avatarUrl": "https://avatars.githubusercontent.com/u/44733905?u=470f5eeb7eaf87f758937748c982d9ba73c4fd95&v=4"
    },
    "labels": [
      {
        "id": "LA_kwDOMT5cIs8AAAABrA0qWA",
        "name": "bug",
        "color": "d73a4a",
        "description": "Something isn't working"
      }
    ],
    "comments": [
      {
        "id": "IC_kwDOMT5cIs6Y3Smv",
        "author": "github-actions",
        "body": "Hello @yqj1941! Welcome to the ai16z community. Thank you for opening your first issue; we appreciate your contribution. You are now a ai16z contributor!"
      },
      {
        "id": "IC_kwDOMT5cIs6Y32gO",
        "author": "askwhyharsh",
        "body": "deleted post\r\n"
      }
    ]
  },
  {
    "id": "I_kwDOMT5cIs6koqVK",
    "number": 1556,
    "title": "TWITTER_TARGET_USERS cant use names starting with digits",
    "body": "If you have a twitter account starting with a number, it appears to throw an error.\r\n\r\n**To Reproduce**\r\nModify TWITTER_TARGET_USERS in youir .env file that uses an account starting with a digit\r\n```\r\nTWITTER_TARGET_USERS=\"someuser,1someuser\"\r\n```\r\n\r\n**Expected behavior**\r\nNo error should occur, and application should continue running\r\n\r\n**Screenshots**\r\nError produced:\r\n`[\"⛔ Error: Twitter configuration validation failed:\\nTWITTER_TARGET_USERS.2: Invalid Twitter username format\"] `\r\n\r\n**Additional context**\r\nIt wasn't clear, but using true account names with the @ prefix was not the expected input either, although my assumption was to use them.  Once I found it not working I tried different ways to use the field.\r\n",
    "state": "OPEN",
    "createdAt": "2024-12-29T06:13:16Z",
    "updatedAt": "2024-12-29T08:18:54Z",
    "author": {
      "login": "cre8tions",
      "avatarUrl": "https://avatars.githubusercontent.com/u/2237676?v=4"
    },
    "labels": [
      {
        "id": "LA_kwDOMT5cIs8AAAABrA0qWA",
        "name": "bug",
        "color": "d73a4a",
        "description": "Something isn't working"
      }
    ],
    "comments": [
      {
        "id": "IC_kwDOMT5cIs6Y3RaS",
        "author": "github-actions",
        "body": "Hello @cre8tions! Welcome to the ai16z community. Thank you for opening your first issue; we appreciate your contribution. You are now a ai16z contributor!"
      },
      {
        "id": "IC_kwDOMT5cIs6Y3XL7",
        "author": "oxSaturn",
        "body": "Seems It's already fixed on the develop branch https://github.com/elizaOS/eliza/commit/c84b33cfc2ae85fbb86349c19ffa237439668493."
      }
    ]
  },
  {
    "id": "I_kwDOMT5cIs6kokU_",
    "number": 1552,
    "title": "Quick start guide bug - pnpm start",
    "body": "**Describe the bug**\r\nwhen going through the quickstart guide\r\n\r\nGetting an error when using local client (`pnpm start:client`) and init any chat such as `hello`...the output on the service is:\r\n\r\n```\r\n-0009-a2c3-83780c350ff3 successfully.\"] \r\n\r\n [\"◎ Agent tate linked to room 6ac3f59a-67bb-0009-a2c3-83780c350ff3 successfully.\"] \r\n\r\n ◎ LOGS\r\n   Creating Memory \r\n   0c8b6c1c-00b2-0768-8309-564c7d224967 \r\n   hi \r\n\r\n [\"◎ Generating message response..\"] \r\n\r\n [\"◎ Generating text...\"] \r\n\r\n ℹ INFORMATIONS\r\n   Generating text with options: \r\n   {\"modelProvider\":\"gaianet\",\"model\":\"large\"} \r\n\r\n ℹ INFORMATIONS\r\n   Selected model: \r\n   qwen72b \r\n\r\n ◎ LOGS\r\n   Creating Memory \r\n   2f8f543d-8105-094e-89e8-5ecda88f310f \r\n   What's the purpose of this conversation? \r\n\r\n\r\nfile:///Users/dev/rsrc/eliza/packages/adapter-sqlite/dist/index.js:308\r\n        const memories = this.db.prepare(sql).all(...queryParams);\r\n                                              ^\r\nSqliteError: Vector dimension mistmatch. First vector has 768 dimensions, while the second has 384 dimensions.\r\n    at SqliteDatabaseAdapter.searchMemoriesByEmbedding (file:///Users/dev/rsrc/eliza/packages/adapter-sqlite/dist/index.js:308:47)\r\n    at SqliteDatabaseAdapter.createMemory (file:///Users/dev/rsrc/eliza/packages/adapter-sqlite/dist/index.js:240:48)\r\n    at MemoryManager.createMemory (file:///Users/dev/rsrc/eliza/packages/core/dist/index.js:3176:44)\r\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\r\n    at async file:///Users/dev/rsrc/eliza/packages/client-direct/dist/index.js:275:13 {\r\n  code: 'SQLITE_ERROR'\r\n}\r\n\r\nNode.js v23.3.0\r\n/Users/dev/rsrc/eliza/agent:\r\n ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @elizaos/agent@0.1.7-alpha.2 start: `node --loader ts-node/esm src/index.ts \"--isRoot\" \"--character=characters/tate.character.json\"`\r\nExit status 1\r\n ELIFECYCLE  Command failed with exit code 1.\r\n```\r\n\r\n<!-- A clear and concise description of what the bug is. -->\r\n\r\n**To Reproduce**\r\n- `pnpm start --character=\"characters/tate.character.json\"`\r\n-  `pnpm start:client`\r\n-  initiate a chat after selecting agent - such as 'hello'\r\n- no response on UI; the service has the error above with the service process exiting code 1\r\n<!-- Steps to reproduce the behavior. -->\r\n\r\n**Expected behavior**\r\n\r\n<!-- A clear and concise description of what you expected to happen. -->\r\n\r\n**Screenshots**\r\n\r\n<!-- If applicable, add screenshots to help explain your problem. -->\r\n\r\n**Additional context**\r\n\r\nstarts up just fine, creates memories etc to the vector db.\r\n\r\nusing node version 23.3, tried 24.3 - same result\r\non a mac os - Monterrey - 12.7.6 (intel chip)\r\n\r\nusing elizaOS version - `v0.1.7-alpha.2`\r\nusing `gaianet` as the model provider\r\n\r\n<!-- Add any other context about the problem here. -->\r\n",
    "state": "OPEN",
    "createdAt": "2024-12-29T04:17:01Z",
    "updatedAt": "2024-12-29T04:18:25Z",
    "author": {
      "login": "freddymercury",
      "avatarUrl": "https://avatars.githubusercontent.com/u/22851546?u=30fdc2d51e9fb1f838f38658900d96830b9f8d17&v=4"
    },
    "labels": [
      {
        "id": "LA_kwDOMT5cIs8AAAABrA0qWA",
        "name": "bug",
        "color": "d73a4a",
        "description": "Something isn't working"
      }
    ],
    "comments": [
      {
        "id": "IC_kwDOMT5cIs6Y3Mzl",
        "author": "github-actions",
        "body": "Hello @freddymercury! Welcome to the ai16z community. Thank you for opening your first issue; we appreciate your contribution. You are now a ai16z contributor!"
      }
    ]
  }
]
